module.exports = {
  data: [
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 0,
      incognito: false,
      index: 0,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "qwer",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    },
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 1,
      incognito: false,
      index: 1,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "asdf",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    },
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 2,
      incognito: false,
      index: 2,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "qwer1",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    },
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 3,
      incognito: false,
      index: 3,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "asdf1",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    },
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 4,
      incognito: false,
      index: 4,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "qwer2",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    },
    {
      active: false,
      audible: false,
      favIconUrl: "",
      height: 683,
      highlighted: false,
      id: 5,
      incognito: false,
      index: 5,
      mutedInfo: Object,
      pinned: false,
      selected: false,
      status: "complete",
      title: "asdf2",
      url: "chrome://bookmarks/#1",
      width: 1366,
      windowId: 1
    }
  ]
};